const orderHistory = [
  {
    orderPlaced: 'August 2, 2020',
    totalCost: '$34.00',
    shipTo: 'JS Masher',
    orderNumber: '114-3941689-8772232',
    deliveryDate: 'August 8, 2020',
    itemTitle: 'JavaScript for impatient programmers',
    author: 'Rauschmayer, Dr. Axel',
    returnWindow: 'Closed on Sep 7, 2020',
    productType: 'Book',
    packageDelivered: true,
    methodOfDelivery: 'Handed directly to resident',
  },
  {
    orderPlaced: 'July 19, 2020',
    totalCost: '$44.53',
    shipTo: 'JS Masher',
    orderNumber: '113-9984268-1280257',
    deliveryDate: 'July 20, 2020',
    itemTitle: 'The Timeless Way of Building',
    author: 'Alexander, Christopher',
    returnWindow: 'Closed on Aug 19, 2020',
    productType: 'Book',
    packageDelivered: true,
    methodOfDelivery: 'Handed directly to resident',
  },
  {
    orderPlaced: 'July 4, 2020',
    totalCost: '$17.22',
    shipTo: 'JS Masher',
    orderNumber: '114-2875557-9059409',
    deliveryDate: 'July 7, 2020',
    itemTitle:
      'Gamecube Controller Adapter. Super Smash Bros Switch Gamecube Adapter for Wii U, PC. Support Turbo and Vibration Features. No Driver and No Lag-Gamecube Adapter',
    author: null,
    returnWindow: 'Closed on Aug 5, 2020',
    productType: 'Controller Adapter',
    packageDelivered: true,
    methodOfDelivery: 'Handed directly to resident',
  },
  {
    orderPlaced: 'July 3, 2020',
    totalCost: '$138.93',
    shipTo: 'JS Masher',
    orderNumber: '113-2883177-2648248',
    deliveryDate: 'July 5, 2020',
    itemTitle:
      'GameCube Controller - Super Smash Bros Edition (Nintendo Switch)',
    itemTitle2: 'The Art of Sql',
    author: 'Faroult, Stephane',
    returnWindow: 'Closed on Aug 4, 2020',
    productType: 'Controller',
    productType2: 'Book',
    packageDelivered: true,
    methodOfDelivery: 'Delivered',
  },
];
console.log(orderHistory);
